---
# This playbook will generate and apply configuration to all of the devices

- import_playbook: make-directory.yaml

- name: Create configuration for leaf devices
  hosts: leaf
  connection: local
  gather_facts: no
  roles:
    - junos-system
    - junos-ebgp
    - build-config

- name: Create configuration for Spine devices
  hosts: spine
  connection: local
  gather_facts: no
  roles:
    - junos-system
    - junos-ebgp
    - build-config
