

underlay:
    local:
        asn: 65002
    neighbors:
      - interface: ge-0/0/1
        name: vmx3
        asn: 65101
        peer_ip: 10.10.3.2
        local_ip: 10.10.3.1
      - interface: ge-0/0/2
        name: vmx4
        asn: 65102
        peer_ip: 10.10.4.2
        local_ip: 10.10.4.1
      - interface: ge-0/0/0
        name: vqfx1
        asn: 65103
        peer_ip: 10.10.5.2
        local_ip: 10.10.5.1

